# -*- coding: utf-8 -*-
"""lab9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NBUiQvujt7BXyyvTp8FR-sXYP8tEW77w
"""

import pandas as pd
import numpy as np

data =  pd.read_csv('iris.data', sep=",")
# print(data)
# x1,x2,x3,x4=data[:,0:4]
# y=data[:,5]

x=data.iloc[:,0:4]
y=data.iloc[:,4]
y1=[]
z=x.to_numpy() 

# print(np.dtype)
# print(y)
for i in y:
  if i=="Iris-setosa":
    y1.append(1)
  elif i=="Iris-versicolor":
    y1.append(2)
  else:
    y1.append(3)
y1=np.array(y1)

a_b= np.array([2,2.5,3,4,5.6])
z1=z[:,0]
z2=z[:,1]
z3=z[:,2]
z4=z[:,3]
# print(len(z[:,0]))
MSE=sum(((a_b[0]*z1 + a_b[1]*z2 + a_b[2]*z3 + a_b[3]*z4 + a_b[4])-y1)**2)/len(z[:,0])
print(MSE)



